@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_TOP_DOWN()

title Component - Orders Service

System_Boundary(orders_sys, "Orders Service") {
  Component(orders_create, "Create Order Use Case", "Application Service", $link="sequence-create-order.svg")
  Component(orders_get, "Get Order Use Case", "Application Service", $link="sequence-get-order.svg")
  Component(orders_repo, "Order Repository", "Persistence Adapter")
  Component(orders_pay, "Payment Gateway Port", "Port")
  Component(orders_promo, "Promo Service Port", "Port")
  Component(orders_fx, "FX Converter", "Service")
  Component(orders_risk, "Risk Checker", "Service")
}

' External dependencies surrounding the microservice
System_Ext(payment_api, "Payment Service", "External payment processor")
System_Ext(promo_api, "Promo Service", "3rd‑party promo/discount API")
SystemDb_Ext(sqlite_db, "SQLite", "Orders persistence (file or memory fallback)", $link="er.svg")

Rel(orders_create, orders_repo, "save(order)")
Rel(orders_create, orders_pay, "charge()")
Rel(orders_create, orders_promo, "getDiscountPercent()")
Rel(orders_create, orders_fx, "convert()")
Rel(orders_create, orders_risk, "isAllowed()")
Rel(orders_get, orders_repo, "get(id)")

' Adapter → External relations
Rel(orders_pay, payment_api, "HTTP charge()")
Rel(orders_promo, promo_api, "HTTP getDiscountPercent()")
Rel(orders_repo, sqlite_db, "SQL read/write")

footer [[https://mundiir.github.io/meetup-2025-landscape/c4-containers.svg Back to Container]]
@enduml
